FROM alpine:latest

ENV JAVA_HOME /usr/lib/jvm/default-jvm
ENV PATH $PATH:$JAVA_HOME/bin

# Install OpenJDK and other necessary packages
RUN apk add --no-cache openjdk11-jre-headless screen

RUN mkdir /minecraft

WORKDIR /minecraft

COPY template/* /minecraft/

RUN chmod +x /minecraft/run.sh

EXPOSE 25565

ENTRYPOINT ["/minecraft/run.sh"]