# Use a base image with Java installed
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /minecraft

RUN wget -O server.jar "https://piston-data.mojang.com/v1/objects/450698d1863ab5180c25d7c804ef0fe6369dd1ba/server.jar"

# Accept Minecraft EULA
RUN echo "eula=true" > eula.txt

# Expose Minecraft default port
EXPOSE 25565

# Command to run Minecraft server
CMD java -Xmx2G -jar server.jar nogui