# Use openjdk 17 slim base image
FROM openjdk:17-jdk-slim

# Install curl
RUN apt-get update && apt-get install -y curl

# Download Fabric installer
RUN curl -o fabricinstaller.jar https://maven.fabricmc.net/net/fabricmc/fabric-installer/1.0.1/fabric-installer-1.0.1.jar

# Make the jarfile executable
RUN chmod +x fabricinstaller.jar

# Run Fabric Installer
RUN java -jar fabricinstaller.jar server -dir ./mcserver -mcversion 1.20.1 -downloadMinecraft -noprofile

# Copy mods and config from the Docker build context
COPY mods ./mcserver/mods
COPY config ./mcserver/config

# Copy other config files
COPY server.properties ./mcserver/server.properties
COPY usercache.json ./mcserver/usercache.json
COPY ops.json ./mcserver/ops.json
COPY whitelist.json ./mcserver/whitelist.json

# Copy runserver.sh script
COPY runserver.sh ./mcserver/runserver.sh

# Set workdir
WORKDIR /mcserver

# Accept EULA
RUN echo "eula=true" > eula.txt

# Ensure start script is executable
RUN chmod +x runserver.sh

# Expose ports for Minecraft server
EXPOSE 25565/tcp
EXPOSE 25575/tcp

# Start the server using the runserver.sh script
CMD ["./runserver.sh"]